sqlite.database.file.path=/sdk/db/anagrafica.db
client.host=https://nsis.sanita.it/WSHUBPA/interop_new/services/DownloaderAnagrafiche
client.username={username dell'utenza NSIS per chiamare il Gestore Anagrafi}
client.password={password dell'utenza NSIS per chiamare il Gestore Anagrafi}

resilienza.ore=2
