nome.flusso=SIAR_RIAB
regole.percorso=/sdk/regole/regole-siar-riab.xml

xmloutput.percorso=/sdk/xmloutput/SDK_SIAR_RIAB_{{periodoRiferimento}}_{{idRun}}.xml

sent.percorso=/sdk/sent/
flusso.percorso=/sdk/dir/
soglia.invio.mds=50
dimensione.blocco=250000
separatore=~

run.percorso=/sdk/run
esito.percorso=/sdk/esiti
progressivo.percorso=/sdk/progressivo

url.webservice.gaf=https://nsis.sanita.it/WSHUBPA/interop_new/services/GAFWS
user.invio.mds={username utenza NSIS }
password.invio.mds={password utenza NSIS}


gaf.sender.authorizer.type=JWT
url.rest.gaf=https://api.salute.gov.it/api/gaf
gaf.sender.authorizer.token-issuer.url=https://nsis-ids.sanita.it/nidp/oauth/nam/token
gaf.sender.authorizer.token-issuer.grant_type={client_credentials o password }
gaf.sender.authorizer.token-issuer.username={username necessario all'autenticazione tramite servizi rest}
gaf.sender.authorizer.token-issuer.password={password dell'username necessario all'autenticazione tramite servizi rest}
gaf.sender.authorizer.token-issuer.client_id={client_id assegnato dal Ministero della Salute per chiamare i microservizi del gaf}
gaf.sender.authorizer.token-issuer.client_secret={secret del client_id assegnata dal Ministero della Salute per chiamare i microservizi del gaf}
gaf.sender.authorizer.token-issuer.scope={scope assegnati dal Ministero della Salute per chiamare i microservizi del gaf}
gaf.sender.type=REST
rest.ignoreSslVerification=true
