url.webservice.gaf=https://nsis.sanita.it/WSHUBPA/interop_new/services/interop_new/services/GAFPDD
url.webservice.dpm=https://nsis.sanita.it/WSHUBPA/interop_new/services/PMDAT
path.esiti=/sdk/SDK_MONITORAGGIO_ELABORAZIONE_MDS/LOG
path.fus=/sdk/SDK_MONITORAGGIO_ELABORAZIONE_MDS/FUS
path.esiti.mx11=/sdk/SDK_MONITORAGGIO_ELABORAZIONE_MDS/SCARTI_MDS
user.invio.mds={utenza NSIS per l'invio verso il gaf}
password.invio.mds={password NSIS per l'invio verso il gaf}
user.invio.mds.dpm={username NSIS per l'invio verso il servizio dpm}
password.invio.mds.dpm={utenza NSIS per l'invio verso il servizio dpm}